### ISSUE TITLE
Error when using node pack in react

### ISSUE THREAD

**Issue by tiagozaccaro** [formulajs/formulajs#106]
Compile error when using in react.

./node_modules/@formulajs/formulajs/lib/esm/index.mjs 1362:25
Module parse failed: Unexpected token (1362:25)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
|
>   delimiter = delimiter ?? '';
|   let flatArgs = flatten(args);
|   let textToJoin = ignore_empty ? flatArgs.filter(text => text) : flatArgs;

**Comment by nicolashefti** [comment]
@tiagozaccaro can you give us a bit more context? Are you using the library for a long time and something broke recently?

@bornova any thoughts on this one? You worked on the whole module setup for the version 3.0.0.

**Comment by bornova** [comment]
This looks to be related to #99, you could please try the solution posted there for now?  It seems like babel is complaining about the nullish coalescing operator (`??`).  I can create a PR to use a conditional (ternary) operator here instead which would permanently fix the issue.

**Comment by bornova** [comment]
v3.1.5 has been released which hopefully resolves this issue. @tiagozaccaro, could you please try the latest version and let us know if you run into the same issue?

**Comment by tiagozaccaro** [comment]
This version fix the bug, thank you.
