### ISSUE TITLE
there is a bug in round function?

### ISSUE THREAD

**Issue by bokoko** [formulajs/formulajs#109]
ROUND(600.405,2) -> 600.41
ROUND(600.415,2) -> 600.42
ROUND(600.425,2) -> 600.42
ROUND(600.435,2) -> 600.43
ROUND(600.445,2) -> 600.45
ROUND(600.455,2) -> 600.46
ROUND(600.465,2) -> 600.47
ROUND(600.475,2) -> 600.48
ROUND(600.485,2) -> 600.49
ROUND(600.495,2) -> 600.5

**Comment by nicolashefti** [comment]
@bokoko thanks for reporting a bug. Can you give a bit more details? What are your expecting? I guess these are the two lines here: 

```
ROUND(600.425,2) -> 600.42 # Expected 600.43
ROUND(600.435,2) -> 600.43 # Expected 600.44
```

Do you want to propose a PR to fix the issue?

**Comment by bornova** [comment]
Unfortunately, floating point math in JavaScript can produce rounding errors such as in this case.  One way to address this may be to use exponential notation to prevent rounding errors.  Although not bulletproof, I would propose making the following change:

https://github.com/formulajs/formulajs/blob/6440ae72964d943f80862c690c0a834a833a89c8/src/math-trig.js#L914

```diff
- return Math.round(number * Math.pow(10, digits)) / Math.pow(10, digits) 
+ return Number(Math.round(Number(number + 'e' + digits)) + 'e' + digits * -1)
```
