### ISSUE TITLE
float num get a error result

### ISSUE THREAD

**Issue by tenadolanter** [formulajs/formulajs#112]
exec `MINUS(4.1,  4.3)` get `-0.20000000000000018`, expect `-0.2`

**Comment by bornova** [comment]
Hi @tenadolanter,
I am afraid this is not an issue with formulajs but rather a javascript issue in general handling floating point numbers.  You can try `4.1-4.3` in your console for example and you will see that result will also be `-0.20000000000000018`.

Here is an article explaining this in detail: https://www.matthewburfield.com/javascript-deep-dive-floating-point-numbers/
