### ISSUE TITLE
Cannot find module '@formulajs/formulajs'

### ISSUE THREAD

**Issue by andrewbihl** [formulajs/formulajs#116]
I am getting the persistent error: @formulajs/formulajs

I am running a NodeJS + Typescript app. Latest version of formulajs. Node version v17.8.0.

**Comment by nicolashefti** [comment]
Hi @andrewbihl, can you provide a little setup / gist / test repo to reproduce the error ?

**Comment by phucpnt** [comment]
@andrewbihl you need to include the extension `mjs` in webpack resolve extensions. Eg
```
{
  //....
  resolve: {
    extensions: [ /*...*/, 'mjs']
  }
}
```

**Comment by nicolashefti** [comment]
@andrewbihl is your issue resolved?

**Comment by oleksandr-danylchenko** [comment]
> @andrewbihl you need to include the extension `mjs` in webpack resolve extensions. Eg
> 
> ```
> {
>   //....
>   resolve: {
>     extensions: [ /*...*/, 'mjs']
>   }
> }
> ```

Thanks 🙌🏻 It resolved the issue

**Comment by david-wolgemuth** [comment]
Using `react-scripts` which doesn't give access to webpack config,
there's a workaround (not the cleanest, as it requires another package):

https://github.com/reactioncommerce/reaction-component-library/issues/399#issuecomment-467860022

**Comment by johnnyoshika** [comment]
Similarly I was able to fix this same problem with ts-jest by adding mjs to the extension resolver. In package.json:

```
  "jest": {
    "transform": {
      "^.+\\.m?[tj]sx?$": [
        "ts-jest",
        {
          "diagnostics": {
            "warnOnly": true
          }
        }
      ]
    },
    "testEnvironment": "node"
  },
```
