### ISSUE TITLE
Empty string when parsed as number gives 0 instead of Error

### ISSUE THREAD

**Issue by laucheukhim** [formulajs/formulajs#145]
```
=INT("")
```

In Excel, empty string is parsed as `Error: #VALUE!`.

In Formula.js, empty string is parsed as `0`.

https://github.com/formulajs/formulajs/blob/e9e62d49a946596052922fc23495c9d57a658bb2/src/utils/common.js#L356

**Comment by nicolashefti** [comment]
Hi @laucheukhim. Thanks for reporting. Would you like to propose a PR to fix the issue?
