### ISSUE TITLE
IFERROR error checking mechanism

### ISSUE THREAD

**Issue by sanchit3008** [formulajs/formulajs#158]
In `information.js`, the presence of error is being checked by comparing to an Error object and not the value itself which even causes the demo on the official page to not work.

![image](https://github.com/formulajs/formulajs/assets/22197708/97c4c708-0817-4794-bf00-7b58d904feaf)

Please suggest a fix or workaround for this.

**Comment by nicolashefti** [comment]
@sanchit3008, technically this is correct. The string "#DIV/0!" is not an error, it's a string. If you try the same formula in Excel it will output the same.

DAYS() without parameters will throw and error and will be caught by the IFERRROR. For example:

    IFERROR(DAYS(),"Error") // => "Error"

Can you tell me more about your use case?

**Comment by sanchit3008** [comment]
Thanks for the response @nicolashefti . I am using a spreadsheet package (https://github.com/ruilisi/fortune-sheet/) which is using formulajs to parse user inputted formulae. However, it seems that then the sheet is handling errors in a wrong manner because nothing seems to trigger the error condition in IFERROR then. Does passing any kind of error object trigger the error argument for IFERROR? If yes, then I will propose a fix to fortunesheet maintainers.

Thanks once again for the response.

**Comment by nicolashefti** [comment]
I just checked, IFERROR will only be true in case of one known errors (`error.value, error.ref, error.div0, error.num, error.name, error.nil`).

I guess the easier in your case (to avoid #DIV!) should be to use following workaround: `=IF(A2>0; A1/A2; "Error or default value")`

**Comment by sanchit3008** [comment]
Thanks @nicolashefti
