### ISSUE TITLE
Detach from handsontable/formula.js

### ISSUE THREAD

**Issue by nicolashefti** [formulajs/formulajs#161]
Technically formulajs repo is a fork from handsontable/formula.js. We are just 130 commits ahead :)

Everytime I create an PR, I need to change the default settings from Github to avoid creating a PR on the main handsontable/formula.js.

Is this possible to "detach" from the original repo? Would that make sense technicaly and in terms of meaning for the project?

**Comment by bornova** [comment]
I like the idea.  Github support should be able to make that happen.

**Comment by bornova** [comment]
I say go for it! 🚀

**Comment by nicolashefti** [comment]
We are officially independent!
