### ISSUE TITLE
EDATE() returns incorrect values; adds days and moves into next month

### ISSUE THREAD

**Issue by BobPritchett** [formulajs/formulajs#162]
In Excel and Google Sheets, EDATE() adds or subtracts months. If the day is the last day of the month, and that date does not exist in the new month, the day is clipped to the last day of the month in the target month.

formulaJS tries to make up the missing days in the adjacent month. (This is apparently a side effect of JavaScript's handling for adding/subtracting months.)

In formulaJS, `EDATE(DATE(2023,3,31),-1)` returns `3/3/2023`, which is **incorrect**.

In Excel, it returns `2/28/2023` -- one month earlier, on the last day of the month.

Here is a table of Excel's values for a month earlier and a month later than the date in the first column:

| Date | EDATE(Date,1) | EDATE(Date,-1) |
|--------|--------|--------|
|3/27/2023|4/27/2023|2/27/2023|
|3/28/2023|4/28/2023|2/**28**/2023|
|3/29/2023|4/29/2023|2/**28**/2023|
|3/30/2023|4/30/2023|2/**28**/2023|
|3/31/2023|4/**30**/2023|2/**28**/2023|

**Comment by nicolashefti** [comment]
Hi @BobPritchett, would you like to propose a PR to fix the issue?

**Comment by nicolashefti** [comment]
Merged and released with 4.3.2 @BobPritchett
