### ISSUE TITLE
Call for logo contribution

### ISSUE THREAD

**Issue by nicolashefti** [formulajs/formulajs#166]
Formula.js is now a stand-alone repo. Good time to create logo? Maybe with the help of AI? Anyone willing to propose something?

**Comment by max-prtsr** [comment]
Something around `=JS` maybe?

**Comment by MoOx** [comment]
Took me a few minutes to made this (svg+png)

![logo-formula js](https://github.com/user-attachments/assets/264eb013-2170-4810-b216-00fb03ac6933)
![logo-formula js](https://github.com/user-attachments/assets/5496f11d-ef4f-44c7-a070-9ccc829ed0b1)

**Comment by nicolashefti** [comment]
@MoOx thanks for the proposition. I like the idea around =JS, =FORMULA.JS.

Just wondering how to make an avatar format of it (ex: small square version for the Github repo or website favicon).

**Comment by nicolashefti** [comment]
Thanks @MoOx I made two PNG out of it and finally went for the right aligned logo 🖼️ 

<img width="99" alt="formulajs-centered" src="https://github.com/user-attachments/assets/c9026b91-83ec-44f0-9ec6-88a580572dce">

<img width="125" alt="formulajs-right" src="https://github.com/user-attachments/assets/21d935aa-9f87-405a-9bfd-54dd9e25b7ec">
