### ISSUE TITLE
Have you looked at the https://github.com/davidpolberger/formulajs fork?

### ISSUE THREAD

**Issue by goldsmithjim** [formulajs/formulajs#17]

**Comment by nicolashefti** [comment]
That's totally fitting the [roadmap](https://formulajs.info/about/) for 2020. How do you know about this fork? Do you know some functions developed there and missing in this repo?

The project is quite _offroad_:  160 commits ahead, 142 commits behind sutoiku:master. Maybe never rebased on the original repo after being forked. This might be difficult to compare with this repo.

I'll check if there are stuff to borrow from them.

**Comment by goldsmithjim** [comment]
It's a fork of another fork (now missing) that is now used in production by https://www.calcapp.net/ which I guess is a competitor of yours :-)
I didn't look at it too closely, but it seemed a bit silly to have two companies working on their separate forks!
