### ISSUE TITLE
IRR Formula throwing Infinity

### ISSUE THREAD

**Issue by luzzardi** [formulajs/formulajs#174]
We have a Excel file that calculates IRR and trying to convert it to table and calculate the IRR we are facing an issue with some values.

Here the jsfiddle sample: https://jsfiddle.net/8ztdh72x/4/

`// formulajs version 4.4.0
const netCashFlow = [-15000, 6630]
const irrValue = formulajs.IRR(netCashFlow, 0.1);
document.getElementById('result').innerHTML = irrValue;`

Added the code here if need fiddle get lost.

**Comment by nicolashefti** [comment]
Hi @luzzardi 

You can simply use this page and type your formula: https://formulajs.info/functions/ (without Fiddle)

Using Excel the correct answer:

    =IRR([-15000, 6630], 0.1) // -56% not Infinity

IRR is calculated with an iterative method trying to converge. The JS implementation differs from the Excel one. That being said if you give "a better guess" FormulaJs is able to converge:

     =IRR([-15000, 6630], -0.3) // -0.558

**Comment by luzzardi** [comment]
Hi @nicolashefti 

Perfect! Thanks for the explanations! 
And the change in the guess might help for now thank you!

**Comment by nicolashefti** [comment]
Feel free to propose another implementation of IRR if you need to. There might some other/better ways to calculate that...
