### ISSUE TITLE
Error while converting liter to cubic meter

### ISSUE THREAD

**Issue by narendersaharan94** [formulajs/formulajs#175]
I am using below formula to convert liter into cubic meter, but it is giving error

CONVERT(2000, 'l', 'm3')

**Comment by bornova** [comment]
Thank you for reporting. Looks like a bug indeed.  Here is the problem line:

https://github.com/formulajs/formulajs/blob/9cb435a232ac9775d915ba490a3ad1651f82fa35/src/engineering.js#L488
