### ISSUE TITLE
Creating our own custom formula

### ISSUE THREAD

**Issue by kranthitechie** [formulajs/formulajs#18]
Hi there, 

Is there a way to create our own custom formula? I remember reading this in a documentation somewhere, but unable to locate it now.

Thanks

**Comment by nicolashefti** [comment]
The current documentation is over there: https://formulajs.info/

It is always possible to extend the library. Which Excel function to you need?

**Comment by kranthitechie** [comment]
To count the number of records in an array

**Comment by nicolashefti** [comment]
Have you tried "javascript count the number of records in an array " in Google?

```
const a = [1 , 2 , 3];

// Output is 3
a.length
```

**Comment by kranthitechie** [comment]
Yeah. I was looking for something to turn this into a spreadsheet formula. 

Figured out that we need to use the .setFunction method to create a new formula.
