### ISSUE TITLE
TODAY returns time

### ISSUE THREAD

**Issue by arne-diegenbach** [formulajs/formulajs#19]
The TODAY function returns the time, it should I believe only return the date part. The NOW function show return the date including the time. Thanks.

**Comment by nicolashefti** [comment]
TODAY and NOW both returns JS Date Object. There is in JS no difference between a date and a date with time. There is no way to return "only the date part" as you mentioned.

In formulajs TODAY returns a date of day with time set to 00:00:00 and NOW the date with the current time. In Excel if you have cell with =TODAY() and change the format to include time you will see "00:00:00".

There is an issue #13 and a PR #16 to return always UTC Date.

Does that answer your question?

**Comment by arne-diegenbach** [comment]
Thanks for the quick response.
This would indeed be the behavior I expect, however the TODAY() function returns also the time.
You can see here: https://formulajs.info/functions/

**Comment by nicolashefti** [comment]
Good point. This has been fixed in release 2.4.1, the one of the documentation website is 2.3.3.

I'll update the documentation website.

**Comment by arne-diegenbach** [comment]
I am using 2.4.3.

```
const f = require('@formulajs/formulajs');
console.log( f.TODAY() );
console.log( f.NOW() );
```
2020-07-16T22:00:00.508Z
2020-07-17T12:03:51.511Z

I see for TODAY the hour set to 22:00 in an unknown time zone.
The time returned by NOW() is proper UTC time.

Thanks.

**Comment by arne-diegenbach** [comment]
Hi Nicolas,

To make the TODAY function return the same date as Excel:

```
exports.TODAY = function () {
  var date = new Date();
  return new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), 0, 0, 0));
};
```

If you don't want this and keep your current implementation (returning the wrong date) at least replace the three lines with:

`today.setHours(0,0,0,0);`

To also clear the ms part.

See: [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setHours)

**Comment by nicolashefti** [comment]
It's not the _wrong_ date it's the [_host system_ time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) zone used by default when using new Date().

Apart form the UTC (which is in progress in another PR), TODAY already includes what you expect:

https://github.com/formulajs/formulajs/blob/9b0579692ec38adaadb72cad11a29b5a73b82fef/lib/date-time.js#L435-L441

**Comment by arne-diegenbach** [comment]
1. You are missing the millisecond part while clearing the time. With the `setHours` function you can clear that also (fourth zero) and you need only one instead on three lines of code. That is why functions like `DAYS` and `NETWORKDAYS` return fractions if used with TODAY and they shouldn't.

2. After replacing the `TODAY` function with the above and replacing the `parseDate` function with the following I get perfect answers. `TODAY` returns the right date (same as Excel) and I get the correct answers from the day calculation functions.

```
exports.parseDate = function(date) {
  if (!isNaN(date)) {
    if (date instanceof Date) {
      return new Date(date);
    }
    var d = parseInt(date, 10);
    if (d < 0) {
      return error.num;
    }
    if (d <= 60) {
      return new Date(d1900.getTime() + (d - 1) * 86400000);
    }
    return new Date(d1900.getTime() + (d - 2) * 86400000);
  }
  if (typeof date === 'string') {
    date = new Date(date);

    if (!isNaN(date)) {
        return new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), 0, 0, 0));  // <<<<<<
    }
  }
  return error.value;
};
```

**Comment by nicolashefti** [comment]
You are right about the missing millisecond.  Do you have examples (or even better an Excel file) to illustrate the two problems:
- "DAYS and NETWORKDAYS return fractions if used with TODAY"
- Formula that requires to have UTC Date in the parser.

**Comment by nicolashefti** [comment]
@arne-diegenbach any example for your points 1 and 2? That would help me to write the unit tests.

**Comment by nicolashefti** [comment]
@arne-diegenbach do you have any update for me?

**Comment by nicolashefti** [comment]
@arne-diegenbach I am closing this issue because TODAY is fixed.

Do not hesitate to open a new one, once you have example for what you mentioned about _"DAYS and NETWORKDAYS return fractions if used with TODAY"._
