### ISSUE TITLE
Range parameters for mathematical functions causes ERROR

### ISSUE THREAD

**Issue by gianmarcosanti** [formulajs/formulajs#196]
Hi, I've been playing with the formulas in the playground section of the website to see if the library could help me solve some problems for a project. I noticed that if I want to translate the formula =ABS($M$4:$M$7) to ABS([-7,9,-4]) the library returns "Error: #VALUE!". Is this currently supported by your library? More generally, how do you handle range parameters for your formulas?

**Comment by nicolashefti** [comment]
Hi, ABS does not work with a range of inputs. It's the same in Excel or Google Sheet.

You can loop on the values of your array and apply the ABS function if you need to.

**Comment by gianmarcosanti** [comment]
Hi, thanks for the quick reply! I may have oversimplified the problem, sorry! The formula I worked on is the following:
=INDEX($M$4:$M$35, MATCH(MIN(IF($M$4:$M$35 - J5 >= 0, $M$4:$M$35 - J5, "")), ABS($M$4:$M$35 - J5), 0))

As you can see, ranges are used in IF and ABS. It seems a bit strange to me because I have never seen a formula like this. How does your library handle this use case, if possible?

**Comment by nicolashefti** [comment]
The library does not handle such formula.

Google Sheet (or Excel) neither, it just applies ABS to the first entry of the range.

<img width="224" alt="Screenshot 2024-12-23 at 10 39 30" src="https://github.com/user-attachments/assets/420cee69-930f-4928-b9c2-a616c8b27410" />

**Comment by gianmarcosanti** [comment]
Yes, you are right. Apparently, the MATCH function does some kind of magic that makes IF and ABS work with ranges. As I dug deeper into the library, I realized that you don't support the MATCH function, which is fair enough! I will have to create some js workarounds to handle this case, never mind. Thanks so much for answering!

**Comment by nicolashefti** [comment]
MATCH is supported, but not documented on Formula.js website.

If you use an array formula you could use an non-array formula with an range of elements.

<img width="309" alt="Screenshot 2024-12-23 at 14 26 17" src="https://github.com/user-attachments/assets/939d1ebf-1287-43d5-be5f-dc9b556e8213" />
