### ISSUE TITLE
RATE Function Returning Different Values from Excel?

### ISSUE THREAD

**Issue by azizmars** [formulajs/formulajs#20]
For some reason the RATE function on the library is returning different values compared to excel. Is this a bug or some issue on my end?

> RATE(37,-7200,-40000,4477839,0)

> Excel Returns - 0.001064616396
> Formulajs Returns - 0.010290819255991955

**Comment by nicolashefti** [comment]
Indeed there is bug in the calculations.

Do you want to contribute and propose a pull request to fix it?

**Comment by nicolashefti** [comment]
@azizmars do you want to contribute and propose a pull request to fix it?

**Comment by nicolashefti** [comment]
@azizmars this is now fixed in release 2.5.0.
