### ISSUE TITLE
precision issues

### ISSUE THREAD

**Issue by fscottfoti** [formulajs/formulajs#21]
Javascript has some very frustrating precision issues, e.g. `.2+.1=0.30000000000000004`, which can cause some head-slapping moments with formulajs.

The easiest case I've seen to recreate it is to run `ROUNDUP(.2+.1, 2)` which rounds to `.31` but the correct answer is `.30`.  I assume there are other cases as well.

I'm currently patching ROUNDUP and ROUNDDOWN to reduce precision before rounding.  Has anyone encountered this before - is there any general solution and is this something formulajs should handle?

**Comment by nicolashefti** [comment]
Hi @fscottfoti 

Indeed this has nothing to do with formulajs but with floating point in JS, see https://www.w3schools.com/js/js_numbers.asp

If you have a general approach do not hesitate to propose a PR.

In your case I would add something like: `ROUNDUP(TRUNC(.2+.1, 5), 2)` (can be tested here: https://formulajs.info/functions/)

**Comment by fscottfoti** [comment]
Yes, this is exactly what I do to fix the problem.  I'm just wondering if this should be built into ROUNDUP/ROUNDDOWN.  I imagine there is no general fix, and I don't know how widespread the problem might be.  I did notice that someone else was working on this in a fork here: https://www.npmjs.com/package/formulajs-precision.  And I imagine others have this problem as well...
