### ISSUE TITLE
a known NPER gotcha

### ISSUE THREAD

**Issue by tsanhan** [formulajs/formulajs#22]
the NPER function is missing a case what rate is 0.
please add :
` 
  if(rate === 0) {
    return (- (present + future) / payment);
  }`
to the function, right after the `anyIsError` check

**Comment by nicolashefti** [comment]
Hi @tsanhan 

Can you give an example of a formula in Excel or LibreOffice with the expected result and the current result given by Formula.js?

This would help to write the unit tests related to this fix.

**Comment by nicolashefti** [comment]
@tsanhan this is now fixed in release 2.5.0.

**Comment by tsanhan** [comment]
@nicolashefti thanks.

a simple case is when you have a rate of 0, this input **was** causing the function to break.
