### ISSUE TITLE
MATCH method issue

### ISSUE THREAD

**Issue by zedissime** [formulajs/formulajs#26]
Hello, 

We have discovered a strange behavior using the MATCH method, as you can see on the following screenshot, if the first parameter of match is a string and the lookup values are integers, the match does not work properly.

![image](https://user-images.githubusercontent.com/1235591/102897524-6bc08a00-4468-11eb-9548-e152a75bfce7.png)

I'm using formulajs with xlsx-calc, and, the search value is a number and not a string.
![image](https://user-images.githubusercontent.com/1235591/102897922-10db6280-4469-11eb-881b-b4ab5d69ff95.png)

I'll try to dig more in the code later

**Comment by nicolashefti** [comment]
In Excel the 2nd and 3rd example returns #N/A. If you search a string into an array of numbers you won't fin anything. Is that what you would expect?

I guess you can add one or two tests cases and update the code of the function MATCH. What do you think ?

**Comment by zedissime** [comment]
Yes in fact i can't be sure of the type of the cell, as you can see in my example, B1 is a cell with a number format, but I don't know when, it's converted to a string.
My temporary fix (quick and dirty) is the following :
``` 
...
MATCH: (search, ...rest) => {
  let s = search;
  if (/^[0-9,.]*$/.test(search)) {
     s = parseFloat(search);
  }
  return formulajs.MATCH(s, ...rest);
}
```
As said before i'll try to dig and find why the search would be converted onto a string

**Comment by nicolashefti** [comment]
I close this issue. Don't hesitate to re-open it if you think the problem lies on the library side.
