### ISSUE TITLE
QUESTION: Should DAYS function return the difference as integer or float

### ISSUE THREAD

**Issue by nikazooz** [formulajs/formulajs#28]
Hi!

This is more of a question. Should DAYS function return the difference between end date and start date as an integer, like it currently does, or as a float if date and time is used and there is a fraction left: `DAYS("2021-02-04 01:30:00", "2021-02-03 00:00:00")`

This is coming from my use of LibreOffice, don't know how Excel does things.

Thanks!

**Comment by nicolashefti** [comment]
Hi @nikazooz 

LibreOffice and Excel seem to disagree on this:

- LibreOffice: 1.0625
- Excel: 1
- and Formula.js is just wrong: 2

Based on Excel [definition](https://support.microsoft.com/en-us/office/days-function-57740535-d549-4395-8728-0f07bff0b9df), the integer seem to be correct.

I will check the associated PR in the coming days.

Thanks for the contribution.

**Comment by nikazooz** [comment]
Thank you :slightly_smiling_face:
