### ISSUE TITLE
Feature request:  Support "Mask for workdays" in NETWORKDAYSINTL

### ISSUE THREAD

**Issue by bornova** [formulajs/formulajs#32]
Hi,
Thank you for this amazing library!  One feature I use often in Excel is calculating number of days in a date range for a 3 day or 4 day work week.  Excel's NETWORKDAYS.INTL supports this as defined below (taken from [here](https://exceljet.net/excel-functions/excel-networkdays.intl-function)):

> The NETWORKDAYS.INTL function can also accept a "mask" to specify weekends for the weekend argument. The mask is provided as a string of 7 characters which must be either 1 or zero. In this scheme, the number 1 means weekend and 0 means workday. The first digit represents Monday. Below are some examples:

```javascript
NETWORKDAYS.INTL(start,end,"0101011") // workdays = M,W,F
NETWORKDAYS.INTL(start,end,"1010111") // workdays = Tue, Thu
NETWORKDAYS.INTL(start,end,"1111100") // workdays = Sat,Sun
NETWORKDAYS.INTL(start,end,"0000000") // all workdays, no weekends
```
Would be awesome if formulajs also supported this.

**Comment by nicolashefti** [comment]
Indeed the definition of NETWORKDAYSINTL in formulajs is not as extensive as [the official one from Excel](https://support.microsoft.com/en-us/office/networkdays-intl-function-a9b26239-4f20-46a1-9ab8-4e925bfd5e28).

Do you want to propose a PR to add the string mask of the week?

**Comment by bornova** [comment]
#33

**Comment by nicolashefti** [comment]
Version 2.6.4 tagged and published on npm. Thanks @bornova for your contribution.
