### ISSUE TITLE
Integration with HTML : Uncaught ReferenceError

### ISSUE THREAD

**Issue by chilarai** [formulajs/formulajs#37]
I am facing pretty much a basic issue while integrating formula.js with HTML.  The HTML below gives me `Uncaught ReferenceError: DATE is not defined`. What could be wrong?

```
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/jstat@1.9.2/dist/jstat.min.js"></script> 
        <script src="https://cdn.jsdelivr.net/gh/formulajs/formulajs@2.6.8/dist/formula.min.js"></script>    
    </head>
    <body>
        <script>
            console.log(DATE(2008, 7, 8))
        </script>
    </body>
</html>
```

**Comment by chilarai** [comment]
Oh. It seems, we have to write like this `formulajs.Date(2008, 7, 8)`

**Comment by nicolashefti** [comment]
Hi @chilarai indeed, formulajs does not "leak" all functions into the window Object. You can still do something like this:

```
var formulaKeys = Object.keys(formulajs);
formulaKeys.forEach((key) => {
    window[key] = formulajs[key];
})
```

**Comment by chilarai** [comment]
Thanks. That function really helped. This is what I needed
