### ISSUE TITLE
Rounding big numbers

### ISSUE THREAD

**Issue by AMBudnik** [formulajs/formulajs#4]
Hi Nikolas,

as we no longer proceed on the development of I decided to share this case with you https://github.com/handsontable/formula.js/issues/24

> 9999999999999999+90000000000000000 => result is = 99999999999999999
but this formula in hot-formula-parser equal = > 100,000,000,000,000,000

That's an interesting case. Excel and Google Sheets seem to fail here as well.

**Comment by nicolashefti** [comment]
Hi @AMBudnik 

I'm not sure to understand what has formulajs to do with that issue? This has to do with floating point in JavaScript see: https://www.w3schools.com/js/js_numbers.asp

> Integers (numbers without a period or exponent notation) are accurate up to 15 digits.
> Example
> var x = 999999999999999;   // x will be 999999999999999
> var y = 9999999999999999;  // y will be 10000000000000000 

also 

> var x = 0.2 + 0.1;         // x will be 0.30000000000000004
