### ISSUE TITLE
Type definitions for typescript

### ISSUE THREAD

**Issue by bearkfear** [formulajs/formulajs#42]
Will help too much if in the future you add type definitions for typescript

**Comment by nicolashefti** [comment]
Good idea. Do you want to propose a PR?

**Comment by bearkfear** [comment]
Ok. I Will purpose

Em qua, 5 de mai de 2021 12:07, Nicolas Hefti ***@***.***>
escreveu:

**Comment by bearkfear** [comment]
Better a type definition or covert to typesxript files?

**Comment by nicolashefti** [comment]
@bearkfear I am not sure to understand the difference. Do you have an example or documentation?

**Comment by pbadenski** [comment]
I think the question is whether we prefer:
 1. TypeScript definition file 
 2. or whether should we convert all code to TypeScript.

@nicolashefti Feels like option 1 might be better to start with?

**Comment by nicolashefti** [comment]
Agreed, let's start with the first option.

**Comment by bornova** [comment]
#103
