### ISSUE TITLE
Sandbox SUMIFS function doesn't work

### ISSUE THREAD

**Issue by francoisbillet** [formulajs/formulajs#44]
Hi,
I was reading about SUMIFS function on your documentation and I found an issue that will probably be easily fixed:

![image](https://user-images.githubusercontent.com/37875465/117782364-d6206e00-b241-11eb-9695-e2da77006cd6.png)
 
SUMIFS simulation returns 0 while it should return 12

**Comment by nicolashefti** [comment]
@francoisbillet thanks for reporting the issue. I will have look.

**Comment by nicolashefti** [comment]
@francoisbillet the documentation was using a previous version of the library (2.5.0). The issue has been fixed since version 2.6.2. The simulation is now working as expected.
