### ISSUE TITLE
MATCH method does not strictly match a string with 0 as match_type

### ISSUE THREAD

**Issue by zedissime** [formulajs/formulajs#46]
https://github.com/formulajs/formulajs/blob/db1e5ad6c707f2d036fe0a3a27f859c57224e49a/lib/lookup-reference.js#L39

With this line if you want to match `selected` in `['not_selected', 'not_selected', 'selected', 'not_selected']` you will always get 1. 

In order to keep a strict comparison I would suggest to replace this linked line by something like this :
`String(lookupArray[idx]).toLowerCase() === lookupValue.toLowerCase()`

**Comment by nicolashefti** [comment]
Hi @zedissime thanks for reporting the issue. Could you propose a PR with the update and few unit tests to illustrate the improvement?

**Comment by zedissime** [comment]
Hello @nicolashefti, in fact regarding the related specs, i think it's made on purpose, in order to allow a regex type of match. But for me, it's not a real implementation of the [excel's method ](https://support.microsoft.com/en-us/office/match-function-e8dffd45-c762-47d6-bf89-533f4a37673a). I don't know what's the idea behind this library ?

**Comment by nicolashefti** [comment]
The idea is to follow the real implementation of Excel and check also Libre-/OpenOffice, Google Sheet at the same time.

Some parts haven't change since the early implementation (back in 2014) and might be not correct. Feel free to update/extend the spec as long as the unit tests reflects the behavior of Excel.

**Comment by nicolashefti** [comment]
Hi @zedissime, do you want to propose a PR to solve this issue?

**Comment by nicolashefti** [comment]
Hi @zedissime, do you want to propose a PR to solve this issue?
