### ISSUE TITLE
Use of NA() in some functions doesn't match Excel

### ISSUE THREAD

**Issue by pbadenski** [formulajs/formulajs#47]
With current behaviour formulajs doesn't model the useful properties of "not available" algebra - ie. NA() `op` x = NA()

I've only checked functions mentioned below - this issue might apply to more functions.

Excel | formulajs
------|---------
SUM(NA()) = "#N/A" | SUM(NA())= 0
SUM(NA(), 1) = "#N/A" | SUM(NA(), 1)= 1
SUM(1, NA()) = "#N/A" | SUM(1, NA())= 1

Excel | formulajs
------|---------
ADD(NA()) = "#N/A" | ADD(NA())= "#VALUE!"
ADD(NA(), 1) = "#N/A" | ADD(NA(), 1)= "#VALUE!"
ADD(1, NA()) = "#N/A" | ADD(1, NA())= "#VALUE!"

MINUS, MULTIPLY & DIVIDE have the same problem as ADD

Separately - I was wondering whether JS null should be seen as equivalent to Excel's NA() in terms of semantics.

**Comment by nicolashefti** [comment]
Hi @pbadenski, thanks for reporting the inconsistency. Can you propose a PR to correct the behavior of these functions ?

I think that in terms of edge cases and error returning there are a lot of similar differences between formulajs and Excel.

Regarding the last point #N/A (Excel) being similar to null (JS) : I will answer and the other thread #48

**Comment by nicolashefti** [comment]
@pbadenski I think we are done with this one?

**Comment by pbadenski** [comment]
Correct, thanks - I'm closing.
