### ISSUE TITLE
Update library compilation

### ISSUE THREAD

**Issue by nicolashefti** [formulajs/formulajs#58]
Tasks:
- [ ] ES compatibility target ?
- [ ] Webpack update
- [ ] Add auto build and deploy to NPM, based on release creation
- [ ] Add jshint in Travis and build steps

**Comment by pbadenski** [comment]
Thoughts on switching to esbuild instead of updating webpack?

**Comment by nicolashefti** [comment]
Webpack is already setup. The build is stable and already fast (which seem to be the selling point of esbuild). I do not see much pros, but I do not have much experience with esbuild.

What advantages do you see?

**Comment by pbadenski** [comment]
I only thought it could be interesting and easy enough :)

Not that I think it matters in this case - esbuild indeed is crazy fast. For this project webpack takes 500ms without minification and 2 seconds with minification. Esbuild takes 30ms for either task.

**Comment by pbadenski** [comment]
rxjs had a similar conversation a while back (https://github.com/ReactiveX/rxjs/issues/5270). Feels like the conclusion they reached should be reasonable here too - move to es6 (es2015) to start with?

**Comment by bornova** [comment]
Hey everyone,
After seeing @nicolashefti's initial comment, I decided to take it a step further and started a side repo to refactor formulajs into ES modules if you would be interested: [@bornova/formulajs](https://github.com/bornova/formulajs)

Made the following changes:
- Refactor entire codebase to ES module. Move source code to `src` folder.  Overall formulajs functionality is unchanged.
- Use Prettier for code formatting.
- Updated dev-dependencies:
	- Replace `blanket` with `c8` for code coverage. `c8` is similar to Istanbul (nyc) but has built-in ES modules support.
	- Replace `browserify` and `webpack` with `rollup`. I don't think browserify is needed anymore and I think webpack is a bit overkill for this project.
	- Update to `cli-table3` (cli-table is no longer maintained) to show implementation stats.  Although, no node `bin` support for now.
	- Remove `http-server`.  Use `mochawesome` html reporter instead.
	- Replace `jshint` with `eslint`.
	- Update `mocha` to latest version.
	- Update `should` to latest version.

- New build workflow:
	- Use `rollup` to bundle for three separate targets into `lib` folder: ESModule (.mjs), CommonJS (.cjs), and UMD (.js) for browsers. This folder is not to be included in the repo.  Only created during build process and made available in published bundle.
	- Minify using `Terser`. Final minimized bundle size is now smaller but not by much.
	- Add lint step before build and Travis CI.
	- Update `package.json` so the package can be used in dual-mode. It can be used with both `require` and `import` when installed as NPM package for backward compatibility.
	
- Use GitHub Actions to automatically publish to NPM upon creating a new release.
	- Removed `.npmignore` and use `files` property of package.json to only include the lib folder when published to NPM.

- Remove Makefile and use package.json scripts instead.

I know the changes I made are highly opinionated, based on my personal choices but I am open to feedback/suggestions if you think this may be a good direction forward for this awesome package!  Just wanted to throw this out there and maybe get the conversation going.  Would be happy to create a PR with my changes if there is interest.

**Comment by nicolashefti** [comment]
@bornova that looks like a very good candidate for a version 3.X! Thanks a lot for the detailed approach.

I just created a `version-3` branch. Can you open a PR from your master on this branch, to a get a first feeling of whole diffs?

### Dev dependancies

That’s a very good idea to make some clean up and updates.

### Build

I have no experience with `rollup`. But I agree, we do not use much of `webpack` potential here.

There was the question about ES compatibility target. Did you include `babel` or equivalent ? Or is it included in `rollup`?

Not sure about `Terser` if it does bring much here.

### GitHub Actions

Automatic publication on NPM would be a great improvement in the day-to-day management of the repo.

In your scenario this link would not work anymore, because of missing compiled files in the repo?  https://cdn.jsdelivr.net/gh/formulajs/formulajs@2.9.3/dist/formula.min.js

**Comment by bornova** [comment]
Hi @nicolashefti,
> Can you open a PR from your master on this branch, to a get a first feeling of whole diffs?

Just created a PR with all the proposed changes. (https://github.com/formulajs/formulajs/pull/92)

> Did you include babel or equivalent ? Or is it included in rollup?

I didn't include babel but we can with `@rollup/plugin-babel` plugin. Current target is es6 but can transpile to es5 if needed.

> Not sure about Terser if it does bring much here.

I used `terser` only to produce the minified formula.min.js UMD file.

> In your scenario this link would not work anymore, because of missing compiled files in the repo?

Unfortunately not as I set it up, because that link points to the `dist` folder which would no longer exist.  However, we have couple  options:
- We can decide to bundle into a `dist` folder instead of `lib`.  Then, placing the browser files in the root of the `dist` folder and keeping the `dist` folder in the repo would keep the link structure intact.  V3 link then would be https://cdn.jsdelivr.net/gh/formulajs/formulajs@3.0.0/dist/formula.min.js
- We can switch to npm going forward and V3 link would be https://cdn.jsdelivr.net/npm/@formulajs/formulajs@3.0.0/lib/browser/formula.min.js
  But the old link would still work for older versions according to the note [here](https://github.com/jsdelivr/jsdelivr#github).
  I personally prefer this approach.

**Comment by nicolashefti** [comment]
@bornova @pbadenski FormulaJs has been automatically released in version 3.0.0 on NPM using Github Action!

@bornova thanks a lot for this massive upgrade of all workflow and dependency. Would you like to join the Github organisation?

**Comment by bornova** [comment]
@nicolashefti
Absolutely! Would love to join the organisation.  Thank you for all the work in this library.
