### ISSUE TITLE
Expose error constructors

### ISSUE THREAD

**Issue by pbadenski** [formulajs/formulajs#59]
Could we expose error constructors aka `utils.error`?

It necessary for us to integrate the library into our application. Logic in formulajs library depends on referential equality (`===`) for comparison. We need to use errors and so need to get them from utils to make it work.

**Comment by nicolashefti** [comment]
It's a good idea to be able to get the "domain" errors thrown by the library.

Are you using the library in a backend application or in a browser?

**Comment by pbadenski** [comment]
in a browser.

**Comment by pbadenski** [comment]
Do you have any thoughts on how to expose this? Currently all functions are exported in a default namespace. What we do - is to register all functions into formula engine. I think that more people might be doing the same. If I add a non-excel-function export to the namespace people might want to exclude it. Perhaps export it as "{ utils: { errors: { ... } } }" ? Then people can filter out "utils"?

**Comment by nicolashefti** [comment]
I was wondering the same. I am searching for an example in another open-source library without success so far.
I guess the .utils is a good option.

**Comment by pbadenski** [comment]
I'll go ahead and submit a pull request for this then
