### ISSUE TITLE
CUMIPMT - different results between Excel and formula.js

### ISSUE THREAD

**Issue by dariorinaldi** [formulajs/formulajs#6]
Hello, 
I'm implementing a loan calculation and inside the algorithm, I have to use the `CUMIPMT` function to calculate the interests. 
I tested the results obtained by the `CUMIPMT` function from Excel, OO or Google Sheet with the results returned by the `formula.js` one, and I noticed that with type parameter set to 0, the results are pretty identical, while with a type of 1 the results are very different.

```javascript
CUMIPMT(0.005333, 120, 737.17, 1, 120, 0);

// Results:
// Excel, OO, Google Sheets:
-262.766924283291000

// formula.js
-262.766924283290823

CUMIPMT(0.005333, 120, 737.17, 1, 120, 1);

// Results:
// Excel, OO, Google Sheets: 
-257.462548900007000

// formula.js
-261.373021957193112
```
Am I missing something?

Thank you!

**Comment by nicolashefti** [comment]
Thanks for the detailed investigation. I'll have a look.

**Comment by nicolashefti** [comment]
@dariorinaldi version 2.3.2 just released fixed your issue. There was a little bug in function implementation (compared to LibreOffice code base).

**Comment by dariorinaldi** [comment]
Thanks a lot!
