### ISSUE TITLE
是否支持跨sheet公式

### ISSUE THREAD

**Issue by Sakura2Huiliyi** [formulajs/formulajs#62]
您好, 该项目很棒!
就目前来看, 是否可以像excel一样, 能进行跨sheet公式的计算了. 如果可以那就更好了

**Comment by pbadenski** [comment]
Translated question:
"Hello, this project is great!
For now, is it possible to calculate cross-sheet formulas like excel? If it can, it would be better"

This project only implements functions and not the parsing/evaluation of entire formula. For parsing/evaluation you'd want to take a look at eg. https://www.npmjs.com/package/hot-formula-parser.

**Comment by Sakura2Huiliyi** [comment]
好的, 谢谢您的回复!
