### ISSUE TITLE
CUMIPMT show wrong result

### ISSUE THREAD

**Issue by dlrdelarocha** [formulajs/formulajs#69]
Hi, 
when CUMIPMT function is called in excel or  with handsontable library  with  the followin data 
returns:

=CUMIPMT(0.81%,240,1000000,1,240,0)
= -1,271,706.17
@see https://handsontable.github.io/ruleJS/

On other side, CUMIPMT function is called in formulajs returns:
=CUMIPMT(0.81,240,1000000,1,240,0)
= -3.8302455581682754e+51
@see  https://formulajs.info/functions/

Gran trabajo 🥇

**Comment by nicolashefti** [comment]
I guess the equivalent of

=CUMIPMT(0.81%,240,1000000,1,240,0)

would be (0.0081 instead of 0.81):

=CUMIPMT(0.0081,240,1000000,1,240,0)

In the this case the result is correct on https://formulajs.info/functions/

**Comment by dlrdelarocha** [comment]
Correct, thanks for answering
![image](https://user-images.githubusercontent.com/15334264/134223408-43323f49-6f9c-448f-9168-e8d69f56519a.png)

**Comment by nicolashefti** [comment]
You're welcome.
