### ISSUE TITLE
`DAYS360` - The third argument should be optional.

### ISSUE THREAD

**Issue by manuphatak** [formulajs/formulajs#80]
## Problem

In excel, the 3rd argument in `DAYS360` is optional. However, in the tool, it is required.

https://support.microsoft.com/en-us/office/days360-function-b9a509fd-49ef-407e-94df-0cbda5718c2a

![image](https://user-images.githubusercontent.com/5052422/143776102-cea80e62-126d-4211-bb7d-0558230c1ace.png)

## Related Links

- I originally thought this was a documentation error -  https://github.com/formulajs/formulajs.info/pull/7
- `DAYS360` source code  - https://github.com/sutoiku/formula.js/blob/f52b7efd424036fdd708c9de3ac501f41d595d8c/lib/date-time.js#L114-L150

**Comment by nicolashefti** [comment]
Hi @manuphatak, do you want to propose a pull request?

**Comment by manuphatak** [comment]
Sure!  I can do that 👍
