### ISSUE TITLE
Bug: EXACT() returns always true in v2.9.2

### ISSUE THREAD

**Issue by gbtec-ext-fabioiglesias** [formulajs/formulajs#81]
Hello, I noticed that in the latest versions executing EXACT formula returns true even though the arguments are not equal.

[Here](https://stackblitz.com/edit/angular-ivy-no7muq?devtoolsheight=33&file=src/app/app.component.ts) is a stackblitz demonstrating it

`console.log(FORMULA.EXACT('Word', '0'));` logs true

The latest working version I tried is the one deployed in https://formulajs.info/functions/, which seems to be 2.6.9

Thank you!

![image](https://user-images.githubusercontent.com/48560330/148067459-4366419c-860c-4b76-9008-3c558d7450a4.png)

**Comment by nicolashefti** [comment]
@gbtec-ext-fabioiglesias thanks for reporting the issue. I'll investigate.

**Comment by manuphatak** [comment]
One thing I noticed, none of the tests check the "false" state:

https://github.com/formulajs/formulajs/blob/5c033102658d86f34cee89b6edd77959c225651d/test/text.js#L71-L81

**Comment by manuphatak** [comment]
I'm on a hot streak here, I'm going to a PR
