### ISSUE TITLE
TRIM() failed to remove tab characters

### ISSUE THREAD

**Issue by zukilover** [formulajs/formulajs#86]
Thank you for the powerful library.

I have found a bug on TRIM function. Trimming input below, failed to remove tab characters.

```
Address 1,				
Address 2,
 
Postcode,			
 
Country
```
I've tested on the online editor as well (https://formulajs.info/functions/), it results in the same output.

**Comment by nicolashefti** [comment]
@zukilover do you want a PR to fix the issue?

**Comment by nicolashefti** [comment]
Fixed with release 2.9.3.
