### ISSUE TITLE
babel-loader error when using formula.js

### ISSUE THREAD

**Issue by Jatin-MYST** [formulajs/formulajs#99]
I am trying to use formulajs in a react project.

I get the following error.
![image](https://user-images.githubusercontent.com/72418976/167351907-774dcf83-e39d-4fb7-8099-da8a3729da37.png)

I have tried many ways to solve the problem. 
I'm assuming the problem is with babel but using ?? in the main project works just fine. (I'm new to babel)
Babel nullish-coalescing-operator isn't fixing the problem. 
here is my current babel config in package.json file:
`"babel": {
  "presets": [
	  "@babel/preset-env",
	  "@babel/preset-react"
  ],
  "plugins": [
	  "@babel/plugin-proposal-nullish-coalescing-operator"
  ]
}`

Any help would be much appreciated.

---------------------------------------------------------------------------------------

After further searching I found a solution [here](https://stackoverflow.com/questions/67552020/how-to-fix-error-failed-to-compile-node-modules-react-leaflet-core-esm-pat) that worked for me. I will close this issue.

**Comment by Jatin-MYST** [comment]
After further searching I found a solution [here](https://stackoverflow.com/questions/67552020/how-to-fix-error-failed-to-compile-node-modules-react-leaflet-core-esm-pat) that worked for me. I will close this issue.

**Comment by aWestbrookFan** [comment]
How did you solve it ？According to your address, I can't either

**Comment by Jatin-MYST** [comment]
I followed the solution listed I linked [here](https://stackoverflow.com/a/67574280)
That fixed it for me.
Turns out I didnt need to do touch babel at all.
So I reverted all the changes I made to babel.
Only thing I needed is that browserslist change mentioned in the SO link.
